name: razorpay_flutter_example
description: Demonstrates how to use the razorpay_flutter plugin.
publish_to: 'none'
version: 1.2.6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  razorpay_web:
    path: ../


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true